services:
  vectors_gateway_db:
    image: postgres:16.4-alpine
    container_name: vectors_gateway_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - vectors_gateway_db_postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: vectors_gateway_qdrant
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333

volumes:
  vectors_gateway_db_postgres_data:
    driver: local
  qdrant_storage:
    driver: local
